# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 2
set_param xicom.use_bs_reader 1
set_msg_config  -id {DRC MDRV-1}  -suppress 
set_msg_config  -id {Vivado_Tcl 4-78}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.cache/wt} [current_project]
set_property parent.project_path {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.3 [current_project]
set_property ip_output_repo {e:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/data.coe}}
add_files {{E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/program.coe}}
read_vhdl -library xil_defaultlib {
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/DFlipFlop.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/clock_div_model.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/control_unit.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/customMux.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/demux.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/inference_unit.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/instruction_register.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/ram_fsm.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/ram_top.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/reg_a_fms.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/reg_a_top.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/registry_bank_fsm.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/registry_bank_top.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/rom_fsm.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/rom_top.vhd}
  {E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/new/FMU.vhd}
}
read_ip -quiet {{E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/ip/register_bank/register_bank.xci}}
set_property used_in_implementation false [get_files -all {{e:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/ip/register_bank/register_bank_ooc.xdc}}]

read_ip -quiet {{E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/ip/reg_a/reg_a.xci}}
set_property used_in_implementation false [get_files -all {{e:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/ip/reg_a/reg_a_ooc.xdc}}]

read_ip -quiet {{E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/ip/rom/rom.xci}}
set_property used_in_implementation false [get_files -all {{e:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/ip/rom/rom_ooc.xdc}}]

read_ip -quiet {{E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/ip/ram/ram.xci}}
set_property used_in_implementation false [get_files -all {{e:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/sources_1/ip/ram/ram_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/constrs_1/new/FMU.xdc}}
set_property used_in_implementation false [get_files {{E:/OUSL/5th Year/EEX7436/EEX7436 Design Project/DPP/DPP.srcs/constrs_1/new/FMU.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top FMU -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef FMU.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file FMU_utilization_synth.rpt -pb FMU_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
