# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Fazeel Nizam/Downloads/DPP/DPP/DPP.srcs/sources_1/ip/reg_a/reg_a.xci
# IP: The module: 'reg_a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fazeel Nizam/Downloads/DPP/DPP/DPP.srcs/sources_1/ip/reg_a/reg_a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'reg_a'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Fazeel Nizam/Downloads/DPP/DPP/DPP.srcs/sources_1/ip/reg_a/reg_a.xci
# IP: The module: 'reg_a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Fazeel Nizam/Downloads/DPP/DPP/DPP.srcs/sources_1/ip/reg_a/reg_a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'reg_a'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
