# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/OUSL/5th Year/EEX7436/EEX7436 DPP 2/DPP/DPP/DPP.srcs/sources_1/ip/rom/rom.xci
# IP: The module: 'rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/OUSL/5th Year/EEX7436/EEX7436 DPP 2/DPP/DPP/DPP.srcs/sources_1/ip/rom/rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/OUSL/5th Year/EEX7436/EEX7436 DPP 2/DPP/DPP/DPP.srcs/sources_1/ip/rom/rom.xci
# IP: The module: 'rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/OUSL/5th Year/EEX7436/EEX7436 DPP 2/DPP/DPP/DPP.srcs/sources_1/ip/rom/rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
